### ISSUE TITLE
Fail start

### ISSUE THREAD

**Issue by hfiguiere** [flathub/org.subsurface_divelog.Subsurface#10]
Sounds like issue #3 that came back.

````
% flatpak run org.subsurface_divelog.Subsurface
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
could not connect to display 
Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.


````

**Comment by hfiguiere** [comment]
This is version `7f8bbea702b36b6dc4d6931b73ea56e25d17342eec8b495e377b70a358c7738b`

**Comment by Alexander-Wilms** [comment]
That's probably caused by the switch to KDE SDK 5.12. Do you encounter the issue with other flatpak'd Qt applications using KDE SDK 5.12?

**Comment by hfiguiere** [comment]
I have flatpaked a few apps using that version of the SDK and they work.

**Comment by Alexander-Wilms** [comment]
Ah, this is the same issue as https://github.com/flathub/org.texstudio.TeXstudio/issues/14

I'll disable Wayland again.
