### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by hfiguiere** [flathub/org.subsurface_divelog.Subsurface#11]
To transparently support HiDPI screen,`--env=QT_AUTO_SCREEN_SCALE_FACTOR=1` should be added to the finish-args. This will tell Qt5 to auto scale properly.

**Comment by Alexander-Wilms** [comment]
Shouldn't this be set in org.kde.Platform?

**Comment by hfiguiere** [comment]
in an ideal world Qt would just handle this itself. but we don't live in an ideal world.

**Comment by TingPing** [comment]
Except Qt contributors actively maintain the kde Platform. Report it against the runtime and they will triage it where it needs to go.
