### ISSUE TITLE
Unable to import data form dive computer with Flathub-Package

### ISSUE THREAD

**Issue by thommmmmy** [flathub/org.subsurface_divelog.Subsurface#18]
### Describe the issue:
- [x] Bug
- [ ] Change request
- [ ] New feature request
- [ ] Discussion request

### Issue long description:
The Flatpack-Package could be a workaround. And subsurface form Flathub is really working. But there is no way to import data from a dive computer. It's like a car, where the engine starts, but if you put in gears and push the clutch, it never starts to move. At the end of the dy, it's all most useless.

### Operating system:
Fedora 30 (Linux)

### Subsurface version:
4.8.4 form Flathub

### Steps to reproduce:
Import data form a dive computer.

### Current behavior:
Error: Unable to open /dev/ttyUSB0 Suunto (Vyper Air)

### Expected behavior:
Be able to import data form a dive computer!

### Additional information:
On earlier Fedora versions data import didn't working without root-privileges. Even that was really alarming.

**Comment by jb2cool** [comment]
Can you check what groups you are in. You will likely need to be a member of the dialout group

**Comment by Alexander-Wilms** [comment]
@thommmmmy Can you try again with the latest version and check if you are in the group mentioned above?

**Comment by thommmmmy** [comment]
I switched to the RPM-Package form https://software.opensuse.org/download.html?project=home:Subsurface-Divelog&package=subsurface 
It works well. 

I'll check the Flathub package, if I'll get time.

**Comment by Alexander-Wilms** [comment]
@thommmmmy Could please try this?

`sudo usermod -a -G dialout <username>`, log out and log in again, then try to import data from a dive computer
