### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by zkanda** [flathub/org.subsurface_divelog.Subsurface#3]
Hello, I'm getting this error when running it on Fedora 27.

Any idea how can I fix this issue?

```
This application failed to start because it could not find or load the Qt platform plugin "flatpak"
in "".

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Reinstalling the application may fix this problem.
```

**Comment by TingPing** [comment]
This will be resolved once #2 is resolved.

**Comment by TingPing** [comment]
Actually seems like it was fixed a few hours ago, can you try updating?

**Comment by Alexander-Wilms** [comment]
Could this be related to https://github.com/KDE/flatpak-kde-runtime/commit/7239cb6409b722e6db32aa1cff2931b19e78cfc0 ?

**Comment by Alexander-Wilms** [comment]
After having run flatpak update, it runs again for me.

**Comment by zkanda** [comment]
Yes, i can confirm that it now works, thanks. Closing
