### ISSUE TITLE
New release (4.8.5) is out now

### ISSUE THREAD

**Issue by jb2cool** [flathub/org.subsurface_divelog.Subsurface#9]
There is a new release of this software that it out now and the Flatpak version is lagging behind. I'd be willing to help keep this up to date but i have zero idea where to start.

**Comment by Alexander-Wilms** [comment]
Thanks for the info. I'll update it to KDE SDK 5.12 and Subsurface 4.8.5.

Each time a new Subsurface Version is released, all modules should be updated to the latest release and one should try running a test build. That's it.
